#!/bin/bash
function_verify () {
  permited=$(curl -sSL "https://raw.githubusercontent.com/ogenio/VPSbot/main/TeleBotGen/Control/Control-Bot")
  [[ $(echo $permited|grep "${IP}") = "" ]] && {
  echo -e "\n\n\n\033[1;31m====================================================="
  echo -e "\033[1;31m       ¡LA IP $(wget -qO- ipv4.icanhazip.com) NO ESTA AUTORIZADA!"
  echo -e "\033[1;31m                CONTACTE A @ChumoGH"
  echo -e "\033[1;31m=====================================================\n\n\n"
  exit;
